"""FastAPI backend for the map visualization web app.

Endpoints:
  GET  /api/health  -> DB existence check
  POST /api/search  -> hybrid_search() + GeoJSON conversion
  GET  /            -> index.html (static file serving)
  GET  /static/*    -> built frontend assets
"""

import json
import re
import asyncio
from contextlib import asynccontextmanager
from pathlib import Path
from functools import partial

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# `main.py` lives at src/app/main.py, so the repo root is three levels up.
ROOT = Path(__file__).parent.parent.parent

from src.common.db import connect_rag, RAG_DB_PATH
from src.app.retrieval import hybrid_search

STATIC_DIR = ROOT / "src" / "static"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Pre-load the RURI v3 310m model (~11s) at server startup.

    Without this, since the default `embedding_source="ruri"`, the first
    semantic/hybrid search query of a demo would eat that 11s load cost live.
    Failures here don't block startup — the model just loads normally on the
    first query instead.
    """
    try:
        from src.app.ruri_query import embed_query_ruri
        embed_query_ruri("ウォームアップ")
        print("[startup] RURI v3 310m のプリウォーム完了")
    except Exception as exc:
        print(f"[startup] RURI プリウォーム失敗（初回クエリ時にロードされます）: {exc}")
    yield


app = FastAPI(title="PLATEAU RAG API", version="1.0.0", lifespan=lifespan)

# Allow CORS from the Vite dev server (port 5173) during development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# Pydantic models
# ============================================================

class SearchRequest(BaseModel):
    query: str
    lon: float | None = None          # Manual override (backward compat).
    lat: float | None = None
    radius_m: float = 500.0
    top_k: int = 10
    use_query_parser: bool = True     # Enable LLM query parsing / geocoding.
    embedding_source: str = "ruri"    # "gemini" or "ruri" (default: ruri).
    response_language: str = "ja"     # "ja" or "en".


class SearchResponse(BaseModel):
    query: str
    answer: str
    elapsed_sec: float
    geojson: dict                             # GeoJSON FeatureCollection (WGS84).
    candidate_count: int
    parsed_query: dict | None = None          # LLM parse result.
    geocoded_location: dict | None = None     # {"lon": ..., "lat": ...}
    clarification_question: str | None = None # When set, search was skipped; frontend shows this as the AI's reply.
    route: str | None = None                  # The chosen search route (structured/semantic/hybrid).
    recommended_ids: list[str] = []           # Building IDs the LLM's answer recommended, in order of appearance.
    embedding_source: str = "ruri"             # The embedding model actually used.
    response_language: str = "ja"             # The response language actually used.


# ============================================================
# Helper: candidates DataFrame -> GeoJSON FeatureCollection
# ============================================================

def _sanitize_storeys(v):
    """Normalize invalid storey counts (e.g. 9999, or >=500) to None."""
    if v is None:
        return None
    try:
        n = int(v)
    except (TypeError, ValueError):
        return None
    return None if n >= 500 or n < 0 else n


# building_chunks.id format: a "bldg_" prefix + UUID (generated by enrichment.py).
_BUILDING_ID_RE = re.compile(
    r"bldg_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)


def extract_recommended_ids(answer: str, candidate_ids: set[str]) -> list[str]:
    """Extract recommended building IDs from the LLM's answer text.

    Deduplicates while preserving first-occurrence order (`dict.fromkeys`),
    then intersects with `candidate_ids` to drop any ID the answer
    hallucinated or carried over from an unrelated prior turn.

    Args:
        answer: The LLM's answer text.
        candidate_ids: IDs from this search's candidate set.

    Returns:
        Recommended IDs, in order of first appearance in `answer`.
    """
    found = _BUILDING_ID_RE.findall(answer)
    deduped = list(dict.fromkeys(found))
    return [id_ for id_ in deduped if id_ in candidate_ids]


def candidates_to_geojson(candidates, recommended_ids: list[str] | None = None) -> dict:
    """Convert `building_chunks` geometry (EPSG:6671) into a GeoJSON FeatureCollection.

    Left-joins `building_geom_meta` (roof/elevation/wall orientation) and
    `building_context_meta` (winter sunlight/prominence/wooden density/major
    road/school/hospital) into the properties when those tables exist,
    falling back to the base query otherwise. Invalid `storeys` values are
    normalized to None.

    `WHERE id IN (...)` returns rows in DuckDB's scan order, not the
    `candidates` ranking order, so results are staged into `feat_map` first
    and features are rebuilt in `candidates`' id order. Each feature's
    properties get a 1-based `rank` and an `is_recommended` flag — the flag
    is computed server-side because MapLibre's paint expressions can't
    reference a dynamic JS array.

    Args:
        candidates: A DataFrame with an `id` column (and optionally `score`),
            in ranking order.
        recommended_ids: Building IDs to flag as `is_recommended`.

    Returns:
        A GeoJSON FeatureCollection dict.
    """
    if candidates is None or candidates.empty:
        return {"type": "FeatureCollection", "features": []}

    recommended_set = set(recommended_ids) if recommended_ids else set()
    ids = candidates["id"].tolist()
    score_map = dict(zip(candidates["id"], candidates["score"])) if "score" in candidates.columns else {}

    # Build the SQL IN-clause string (ids are always DB-generated UUIDs, so
    # this is safe from injection without needing parameterization).
    id_placeholders = ", ".join(f"'{id_}'" for id_ in ids)

    con = connect_rag()
    try:
        existing = {r[0] for r in con.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_name IN ('building_geom_meta', 'building_context_meta')"
        ).fetchall()}
        has_meta = {"building_geom_meta", "building_context_meta"} <= existing

        # Extra columns, only selected when the meta tables exist.
        meta_cols = """,
                g.roof_type_est, g.ground_elev_m, g.roof_area_m2, g.shape_type_est,
                g.wall_ratio_n, g.wall_ratio_e, g.wall_ratio_s, g.wall_ratio_w,
                c.winter_sunlit, c.prominence_m, c.wooden_density_ratio,
                c.nearest_major_road_dist_m,
                c.nearest_school_name, c.nearest_school_dist_m,
                c.nearest_hospital_name, c.nearest_hospital_dist_m""" if has_meta else ""
        meta_join = (
            "LEFT JOIN building_geom_meta g ON b.id = g.id "
            "LEFT JOIN building_context_meta c ON b.id = c.id"
        ) if has_meta else ""

        cur = con.execute(f"""
            SELECT
                b.id,
                ST_AsGeoJSON(
                    ST_Transform(b.geometry, 'EPSG:6671', 'EPSG:4326', always_xy:=true)
                ) AS geom_json,
                b.usage, b.measured_height, b.storeys,
                b.ht_depth_max, b.ht_rank_worst,
                b.rv_depth_max, b.rv_rank_worst,
                b.ts_depth_max, b.ts_rank_worst,
                b.structure_type, b.fire_proof,
                b.nearest_station_name, b.nearest_station_dist_m,
                b.nearest_shelter_name, b.nearest_shelter_dist_m,
                b.nearest_park_name, b.nearest_park_dist_m{meta_cols}
            FROM building_chunks b
            {meta_join}
            WHERE b.id IN ({id_placeholders})
        """)
        colnames = [d[0] for d in cur.description]
        rows = cur.fetchall()
    finally:
        con.close()

    # Stage into an id-keyed dict first, so features can be rebuilt in
    # candidates' ranking order instead of DB scan order.
    feat_map: dict[str, dict] = {}
    for row in rows:
        rec = dict(zip(colnames, row))
        geom = json.loads(rec["geom_json"]) if rec.get("geom_json") else None
        if geom is None:
            continue

        raw_score = score_map.get(rec["id"])
        # route="structured" leaves score NULL in DuckDB, which comes back as
        # pandas.NA — round() would raise on that, so pass None through instead.
        score = round(raw_score, 4) if pd.notna(raw_score) else None

        props = {k: v for k, v in rec.items() if k != "geom_json"}
        props["score"] = score
        props["storeys"] = _sanitize_storeys(props.get("storeys"))
        props["is_recommended"] = rec["id"] in recommended_set

        feat_map[rec["id"]] = {
            "type": "Feature",
            "geometry": geom,
            "properties": props,
        }

    # Rebuild in candidates' id order (= ranking order) and assign rank.
    # IDs excluded from feat_map (null geometry) are naturally dropped here.
    features = []
    for rank, id_ in enumerate(ids, start=1):
        feat = feat_map.get(id_)
        if feat is None:
            continue
        feat["properties"]["rank"] = rank
        features.append(feat)

    return {"type": "FeatureCollection", "features": features}


# ============================================================
# Endpoints
# ============================================================

@app.get("/api/health")
async def health():
    """Check whether the RAG database file exists."""
    return {
        "status": "ok",
        "db_exists": RAG_DB_PATH.exists(),
        "db_path": str(RAG_DB_PATH),
    }


@app.post("/api/search", response_model=SearchResponse)
async def search(req: SearchRequest):
    """The hybrid search endpoint.

    `hybrid_search()` is synchronous, so it's wrapped via `run_in_executor` to
    avoid blocking the event loop.
    """
    if not req.query.strip():
        detail = (
            "Please enter a query."
            if req.response_language == "en"
            else "クエリを入力してください。"
        )
        raise HTTPException(status_code=400, detail=detail)

    loop = asyncio.get_event_loop()
    try:
        result = await loop.run_in_executor(
            None,
            partial(
                hybrid_search,
                query=req.query,
                lon=req.lon,
                lat=req.lat,
                radius_m=req.radius_m,
                top_k=req.top_k,
                use_query_parser=req.use_query_parser,
                embedding_source=req.embedding_source,
                response_language=req.response_language,
            ),
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    # Recommended-ID extraction must happen before GeoJSON conversion, since
    # candidates_to_geojson() needs it to set each feature's is_recommended flag.
    candidates = result["candidates"]
    candidate_id_set = set(candidates["id"]) if candidates is not None and not candidates.empty else set()
    recommended_ids = extract_recommended_ids(result["answer"], candidate_id_set)

    geojson = candidates_to_geojson(candidates, recommended_ids=recommended_ids)

    return SearchResponse(
        query=result["query"],
        answer=result["answer"],
        elapsed_sec=round(result["elapsed_sec"], 2),
        geojson=geojson,
        candidate_count=len(geojson["features"]),
        parsed_query=result.get("parsed_query"),
        geocoded_location=result.get("geocoded_location"),
        clarification_question=result.get("clarification_question"),
        route=result.get("route"),
        recommended_ids=recommended_ids,
        embedding_source=result.get("embedding_source", "ruri"),
        response_language=result.get("response_language", "ja"),
    )


# ============================================================
# Static file serving (production: after `vite build`)
# ============================================================

if STATIC_DIR.exists():
    # Mount built assets at /static/*.
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

    @app.get("/")
    async def index():
        return FileResponse(str(STATIC_DIR / "index.html"))
else:
    @app.get("/")
    async def index_dev():
        return {"message": "開発モード: pixi run dev でフロントエンドを起動してください (port 5173)"}
