"""Hybrid search engine: spatial filter x vector search x LLM answer generation.

Processing flow:
  1. Embed the query text with RURI v3 310m (default, local) or
     `gemini-embedding-001`.
  2. Extract top-K candidates via DuckDB HNSW `array_cosine_similarity`
     (adds an `ST_DWithin` spatial filter when lon/lat are given).
  3. Rerank candidate cards and generate an answer with Gemini 3.5 Flash Lite.

`use_query_parser=True` (default) enables LLM query parsing and geocoding: a
`clarification_question` skips search and returns the question directly;
`height_min` / `usage_include` / `structure_type` / `sort_by_height`
attribute filters are supported; answer generation uses temperature=0 for
reproducibility.

`classify_route()` splits a query into structured/semantic/hybrid routes
based on its structured conditions and semantic residual, and optimizes the
search/embedding calls per route — the structured route skips the embedding
API entirely and resolves purely via SQL.
"""

import os
import re
import sys
import time
import duckdb
import numpy as np
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# `retrieval.py` lives at src/app/retrieval.py, so the repo root is two
# levels up.
ROOT = Path(__file__).parent.parent
from src.common.db import connect_rag, RAG_DB_PATH, wgs84_to_epsg6671
from src.pipeline.gpkg import connect as connect_gpkg

# Embedding dimensionality generated by enrichment.py (gemini-embedding-001: 3072-d).
EMBEDDING_DIM = 3072

# Process-local cache of which meta tables exist. Assumes tables don't
# disappear mid-process (geometry.py/context.py rebuild them in a separate
# process). Call reset_meta_tables_cache() if a re-check is needed, e.g. in tests.
_META_TABLES_CACHE: set[str] | None = None


def _get_meta_tables(rag_con: duckdb.DuckDBPyConnection) -> set[str]:
    """Return which of building_geom_meta/building_context_meta/
    building_chunks_ruri_embed exist (queries the DB only on first call)."""
    global _META_TABLES_CACHE
    if _META_TABLES_CACHE is None:
        _META_TABLES_CACHE = set(rag_con.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_name IN ('building_geom_meta', 'building_context_meta', "
            "'building_chunks_ruri_embed')"
        ).fetchdf()["table_name"])
    return _META_TABLES_CACHE


def reset_meta_tables_cache() -> None:
    """Discard the meta table existence cache (after geometry/context rebuilds, or for tests)."""
    global _META_TABLES_CACHE
    _META_TABLES_CACHE = None


# ============================================================
# Step 4-1: Vector search engine
# ============================================================

def embed_query(text: str) -> list[float]:
    """Embed query text with `gemini-embedding-001`.

    Uses `task_type="RETRIEVAL_QUERY"` (as opposed to `RETRIEVAL_DOCUMENT`,
    used by `enrichment.py` for the document side).

    Args:
        text: The query text.

    Returns:
        A list of `EMBEDDING_DIM` floats.

    Raises:
        RuntimeError: If all retries are exhausted.
    """
    from google import genai
    from google.genai import types

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY が .env に設定されていません。")

    client = genai.Client(api_key=api_key)

    for attempt in range(3):
        try:
            response = client.models.embed_content(
                model="gemini-embedding-001",
                contents=[text],
                config=types.EmbedContentConfig(task_type="RETRIEVAL_QUERY"),
            )
            return list(response.embeddings[0].values)
        except Exception as exc:
            if attempt == 2:
                raise RuntimeError(f"クエリ埋め込み生成に失敗: {exc}") from exc
            wait = 3 * (attempt + 1)
            print(f"  [RETRY {attempt + 1}] {wait}秒後リトライ...")
            time.sleep(wait)


def vector_search(
    rag_con: duckdb.DuckDBPyConnection,
    pq: "ParsedQuery",
    route: str,
    query_vec: list[float] | None,
    lon: float | None = None,
    lat: float | None = None,
    radius_m: float = 500.0,
    top_k: int = 30,
    use_fts: bool = False,
    fts_query_text: str | None = None,
    embedding_source: str = "ruri",
) -> pd.DataFrame:
    """Run the search matching one of the three routes: structured/semantic/hybrid.

    - route="structured": expects `query_vec=None`. Resolves purely via SQL
      (WHERE filter + ORDER BY), no embedding API call. `score` is NULL.
    - route="semantic": vector search over all rows (or the spatial-filtered
      subset), as before.
    - route="hybrid": ranks by `array_cosine_similarity` after applying
      `build_filter_clauses()`'s WHERE filter (HNSW doesn't help once
      filtered — this becomes a brute-force scan, which is fine at 2,958 rows).

    A spatial filter (when lon/lat are given) applies via `ST_DWithin`
    regardless of route.

    When `use_fts=True` and route is semantic/hybrid, fetches `top_k*2`
    vector results, fuses them with `fts_search()`'s BM25 results via
    `rrf_merge()`, and trims to the top `top_k` (`fts_query_text` required).

    When `pq` specifies fields that need `building_geom_meta`
    (orientation_filters/sunlight/roof_type/...) or `building_context_meta`
    (quiet/wooden_dense/school distance_filters/...) but the table doesn't
    exist, raises `RuntimeError` rather than silently ignoring the condition.

    When `embedding_source="ruri"`, left-joins `building_chunks_ruri_embed`
    (RURI v3 310m, 768-d) instead of scoring against `building_chunks.embedding`
    (gemini-embedding-001, 3072-d); `building_chunks` and its HNSW index are
    never touched by this branch.

    Args:
        rag_con: An open connection from `connect_rag()`.
        pq: The parsed query.
        route: One of "structured"/"semantic"/"hybrid", from `classify_route()`.
        query_vec: The query embedding, or None for route="structured".
        lon: Optional spatial filter center longitude (WGS84).
        lat: Optional spatial filter center latitude (WGS84).
        radius_m: Spatial filter radius in meters.
        top_k: Number of candidates to return.
        use_fts: Whether to fuse in BM25 full-text search results.
        fts_query_text: Required when `use_fts=True`.
        embedding_source: "ruri" (default) or "gemini".

    Returns:
        A DataFrame of candidate rows with a `score` column (NULL for
        route="structured"), ordered per `build_order_clause()`.

    Raises:
        RuntimeError: If a required precomputed table is missing.
    """
    from src.app.router import build_filter_clauses, build_order_clause, COLUMN_SOURCE

    fetch_k = top_k * 2 if (use_fts and route != "structured") else top_k

    use_vector = route != "structured"
    if use_vector:
        assert query_vec is not None, "route != 'structured' の場合 query_vec が必須です"
        dim = len(query_vec)
        qvec = np.array(query_vec, dtype=np.float32)
    else:
        dim = EMBEDDING_DIM

    # Check which meta tables exist (process-local cache after first query).
    existing_tables = _get_meta_tables(rag_con)
    has_geom_meta = "building_geom_meta" in existing_tables
    has_context_meta = "building_context_meta" in existing_tables
    has_ruri_embed = "building_chunks_ruri_embed" in existing_tables

    # Raise explicitly when a field requires a precomputed table that doesn't exist.
    _context_targets = {"school", "hospital", "police", "fire", "post"}
    needs_geom = bool(
        pq.orientation_filters or pq.roof_type
        or (pq.sunlight)
        or (pq.sort_by and COLUMN_SOURCE.get(pq.sort_by.key) == "g")
    )
    needs_context = bool(
        pq.sunlight or pq.quiet or pq.wooden_dense
        or any(df.target in _context_targets for df in pq.distance_filters)
        or (pq.sort_by and COLUMN_SOURCE.get(pq.sort_by.key) == "c")
    )
    if needs_geom and not has_geom_meta:
        raise RuntimeError(
            "building_geom_meta が存在しません。先に "
            "`pixi run python -m src.pipeline.geometry` を実行してください。"
        )
    if needs_context and not has_context_meta:
        raise RuntimeError(
            "building_context_meta が存在しません。先に "
            "`pixi run python -m src.pipeline.context` を実行してください。"
        )

    use_ruri = use_vector and embedding_source == "ruri"
    if use_ruri and not has_ruri_embed:
        raise RuntimeError(
            "building_chunks_ruri_embed が存在しません。先に "
            "`pixi run python -m src.pipeline.ruri_embed` を実行してください。"
        )

    if not use_vector:
        score_expr = "NULL AS score"
    elif use_ruri:
        score_expr = f"array_cosine_similarity(r.embedding, ?::FLOAT[{dim}]) AS score"
    elif has_geom_meta:
        score_expr = f"array_cosine_similarity(b.embedding, ?::FLOAT[{dim}]) AS score"
    else:
        score_expr = f"array_cosine_similarity(embedding, ?::FLOAT[{dim}]) AS score"

    # Column selection (geometry omitted to keep the payload light).
    if has_geom_meta and has_context_meta:
        select_cols = f"""
            b.id, b.text_card, b.usage, b.measured_height, b.storeys,
            b.ht_depth_max, b.ht_rank_worst,
            b.rv_depth_max, b.rv_rank_worst,
            b.ts_depth_max, b.ts_rank_worst,
            b.structure_type, b.fire_proof,
            b.nearest_shelter_name, b.nearest_shelter_dist_m,
            b.nearest_station_name, b.nearest_station_dist_m,
            b.nearest_emroute_name, b.nearest_emroute_dist_m,
            b.nearest_park_name, b.nearest_park_dist_m,
            b.nearest_landmark_name, b.nearest_landmark_dist_m,
            {score_expr},
            g.ground_elev_m, g.building_height_m, g.roof_area_m2, g.roof_type_est,
            g.wall_ratio_n, g.wall_ratio_e, g.wall_ratio_s, g.wall_ratio_w,
            g.shape_type_est,
            c.winter_sunlit, c.prominence_m, c.wooden_density_ratio, c.nearest_major_road_dist_m,
            c.nearest_school_name, c.nearest_school_dist_m,
            c.nearest_hospital_name, c.nearest_hospital_dist_m,
            c.nearest_police_name, c.nearest_police_dist_m,
            c.nearest_fire_name, c.nearest_fire_dist_m,
            c.nearest_post_name, c.nearest_post_dist_m
        """
        from_clause = (
            "FROM building_chunks b "
            "LEFT JOIN building_geom_meta g ON b.id = g.id "
            "LEFT JOIN building_context_meta c ON b.id = c.id"
        )
        alias = "b."
        table_aliases = {"b": "b.", "g": "g.", "c": "c."}
    elif has_geom_meta:
        select_cols = f"""
            b.id, b.text_card, b.usage, b.measured_height, b.storeys,
            b.ht_depth_max, b.ht_rank_worst,
            b.rv_depth_max, b.rv_rank_worst,
            b.ts_depth_max, b.ts_rank_worst,
            b.structure_type, b.fire_proof,
            b.nearest_shelter_name, b.nearest_shelter_dist_m,
            b.nearest_station_name, b.nearest_station_dist_m,
            b.nearest_emroute_name, b.nearest_emroute_dist_m,
            b.nearest_park_name, b.nearest_park_dist_m,
            b.nearest_landmark_name, b.nearest_landmark_dist_m,
            {score_expr},
            g.ground_elev_m, g.building_height_m, g.roof_area_m2, g.roof_type_est,
            g.wall_ratio_n, g.wall_ratio_e, g.wall_ratio_s, g.wall_ratio_w,
            g.shape_type_est
        """
        from_clause = "FROM building_chunks b LEFT JOIN building_geom_meta g ON b.id = g.id"
        alias = "b."
        table_aliases = {"b": "b.", "g": "g.", "c": "b."}
    else:
        select_cols = f"""
            id, text_card, usage, measured_height, storeys,
            ht_depth_max, ht_rank_worst,
            rv_depth_max, rv_rank_worst,
            ts_depth_max, ts_rank_worst,
            structure_type, fire_proof,
            nearest_shelter_name, nearest_shelter_dist_m,
            nearest_station_name, nearest_station_dist_m,
            nearest_emroute_name, nearest_emroute_dist_m,
            nearest_park_name, nearest_park_dist_m,
            nearest_landmark_name, nearest_landmark_dist_m,
            {score_expr}
        """
        from_clause = "FROM building_chunks"
        alias = ""
        table_aliases = {"b": "", "g": "", "c": ""}

    if use_ruri:
        from_clause += f" LEFT JOIN building_chunks_ruri_embed r ON {alias}id = r.id"

    # Convert the parsed query's structured conditions into WHERE/ORDER BY clauses.
    where_extra, params_extra = build_filter_clauses(pq, alias=alias, table_aliases=table_aliases)
    order_clause = build_order_clause(pq, route, alias=alias, table_aliases=table_aliases)

    params_head = [qvec] if use_vector else []

    if lon is not None and lat is not None:
        # Spatial filter requested: convert WGS84 -> EPSG:6671.
        tmp_con = connect_gpkg()
        x, y = wgs84_to_epsg6671(tmp_con, lon, lat)
        tmp_con.close()

        extra_where = ("AND " + " AND ".join(where_extra)) if where_extra else ""
        sql = f"""
        SELECT {select_cols}
        {from_clause}
        WHERE ST_DWithin({alias}geometry, ST_Point(?, ?), ?)
        {extra_where}
        {order_clause}
        LIMIT ?
        """
        df = rag_con.execute(sql, params_head + [x, y, radius_m] + params_extra + [fetch_k]).df()
    else:
        # No spatial filter: search all rows (structured/hybrid narrow via
        # the WHERE filter alone).
        extra_where = ("WHERE " + " AND ".join(where_extra)) if where_extra else ""
        sql = f"""
        SELECT {select_cols}
        {from_clause}
        {extra_where}
        {order_clause}
        LIMIT ?
        """
        df = rag_con.execute(sql, params_head + params_extra + [fetch_k]).df()

    # Fuse in BM25 full-text search via RRF (not applied for route="structured").
    # Simplification by design: fts_df is narrowed to the id set already
    # fetched by vector search before merging — i.e. FTS is only used to
    # re-rank existing candidates, never to introduce ids the vector search
    # missed. This avoids candidates with missing columns (text_card etc.)
    # that would occur for rows FTS matched but vector search didn't.
    if use_fts and route != "structured" and fts_query_text and not df.empty:
        from src.app.search_fusion import ensure_fts_index, fts_search, rrf_merge
        # Check for the tokenized FTS table (building_chunks_fts).
        has_fts_index = rag_con.execute(
            "SELECT COUNT(*) FROM information_schema.schemata "
            "WHERE schema_name = 'fts_main_building_chunks_fts'"
        ).fetchone()[0] > 0
        if not has_fts_index:
            print("  FTS インデックス未作成のため作成中...")
            ensure_fts_index(rag_con)
        fts_df = fts_search(rag_con, fts_query_text, top_k=fetch_k)
        fts_df = fts_df[fts_df["id"].isin(set(df["id"]))].reset_index(drop=True)
        if not fts_df.empty:
            df = rrf_merge(df, fts_df, id_col="id")
        df = df.head(top_k).reset_index(drop=True)

    return df


# ============================================================
# Step 4-2: LLM answer generation
# ============================================================

def _fmt_depth(v) -> str:
    """Format a flood depth value: NULL/NaN -> 'なし'."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "なし"
    return f"{v:.1f}"


def _fmt_height(v) -> str:
    """Format a height value: NULL/NaN/-9999.0 (sentinel invalid) -> '不明'."""
    if v is None or (isinstance(v, float) and pd.isna(v)) or v <= 0:
        return "不明"
    return f"{v:.1f}"


def _fmt_dist(v) -> str:
    """Format a distance value: NULL/NaN -> 'データなし'."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "データなし"
    return f"{v:.0f}"


def _fmt_plain(v) -> str:
    """Format a string column: NULL/NaN -> 'なし'."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "なし"
    return str(v)


def _fmt_unknown(v, fmt: str = "") -> str:
    """Format a value: NULL/NaN -> '不明' (used for roof_type_est/ground_elev_m)."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "不明"
    return format(v, fmt) if fmt else str(v)


def _fmt_storeys(v) -> str:
    """Format a storey count: NULL/NaN/>=500 (sentinel values like 9999) -> '不明'.

    The literal "9999階建て" that can appear inside `text_card` is out of
    scope here since that text is frozen in the DB (see limitations.md).
    """
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "不明"
    try:
        n = int(v)
    except (TypeError, ValueError):
        return "不明"
    return "不明" if n >= 500 or n < 0 else str(n)


def _fmt_ratio_pct(v) -> str:
    """Format a 0-1 ratio as 'N%'. NULL/NaN -> '不明'."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "不明"
    return f"{v * 100:.0f}%"


def _fmt_orientation(row) -> str:
    """Format all 4 wall orientation ratios compactly (e.g. 南30/北30/東20/西20).

    Showing only the dominant direction used to confuse users when the
    search condition (e.g. "south-facing") and the displayed value (e.g.
    "north is dominant by a hair") appeared to disagree, so this shows every
    direction instead. No data -> '不明'.
    """
    ratios = [
        ("南", row.get("wall_ratio_s")), ("北", row.get("wall_ratio_n")),
        ("東", row.get("wall_ratio_e")), ("西", row.get("wall_ratio_w")),
    ]
    parts = []
    for label, v in ratios:
        if v is None or (isinstance(v, float) and pd.isna(v)):
            continue
        parts.append(f"{label}{v * 100:.0f}")
    return "/".join(parts) if parts else "不明"


def _fmt_sunlit(v) -> str:
    """Format winter_sunlit (bool/NULL) as ○/×/不明."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "不明"
    return "○" if v else "×"


def build_prompt(query: str, candidates: pd.DataFrame, sort_by=None, response_language: str = "ja") -> str:
    """Build the prompt sent to the LLM.

    Args:
        query: The user's natural-language query.
        candidates: Candidate rows, in ranking order.
        sort_by: `query_parser.SortSpec | None`. Passed by `hybrid_search()`
            when `ParsedQuery.sort_by` was set by a superlative query (e.g.
            "the tallest"). When set, the prompt states explicitly that the
            comparison table is already in the requested order, and narrows
            the recommendation instruction to 1 pick (+2 runners-up).
        response_language: "ja" (default) or "en".

    The comparison table intentionally omits the raw similarity score and any
    "by similarity score" phrasing, to avoid anchoring the LLM on it — score
    is a weak upstream signal and shouldn't be presented as grounds for the
    final answer. Full `text_card` text is attached for only the top 10
    candidates; candidates beyond that appear as table rows only.

    The table's "dominant wall orientation" / "winter sunlight" / "roof" /
    "elevation (m)" columns, plus school/hospital/major-road distance, wooden
    density, and prominence, are all derived at prompt-build time from the
    candidate DataFrame's precomputed columns (`building_geom_meta`/
    `building_context_meta`) — `text_card` itself (frozen in the DB, paired
    with its embedding) is never modified for this.

    Returns:
        The complete prompt string.
    """
    n = len(candidates)

    # Comparison table (all candidates). The first column is the candidate
    # DataFrame's rank, which matches the GeoJSON feature's `rank` property.
    table_lines = [
        "| 順位 | 建物ID | 用途 | 高さ(m) | 階数 | 高潮浸水(m) | 洪水浸水(m) | "
        "津波浸水(m) | 構造 | 耐火 | 駅まで(m) | 避難所まで(m) | "
        "壁面方位(%) | 冬日照 | 屋根 | 形状 | 標高(m) | "
        "学校まで(m) | 病院まで(m) | 幹線道路まで(m) | 木造密度 | 突出(m) |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for i, (_, row) in enumerate(candidates.iterrows()):
        table_lines.append(
            f"| {i + 1} | {row['id']} | {_fmt_plain(row.get('usage'))} | "
            f"{_fmt_height(row.get('measured_height'))} | {_fmt_storeys(row.get('storeys'))} | "
            f"{_fmt_depth(row.get('ht_depth_max'))} | {_fmt_depth(row.get('rv_depth_max'))} | "
            f"{_fmt_depth(row.get('ts_depth_max'))} | {_fmt_plain(row.get('structure_type'))} | "
            f"{_fmt_plain(row.get('fire_proof'))} | {_fmt_dist(row.get('nearest_station_dist_m'))} | "
            f"{_fmt_dist(row.get('nearest_shelter_dist_m'))} | "
            f"{_fmt_orientation(row)} | {_fmt_sunlit(row.get('winter_sunlit'))} | "
            f"{_fmt_unknown(row.get('roof_type_est'))} | {_fmt_unknown(row.get('shape_type_est'))} | "
            f"{_fmt_unknown(row.get('ground_elev_m'), '.1f')} | "
            f"{_fmt_dist(row.get('nearest_school_dist_m'))} | {_fmt_dist(row.get('nearest_hospital_dist_m'))} | "
            f"{_fmt_dist(row.get('nearest_major_road_dist_m'))} | {_fmt_ratio_pct(row.get('wooden_density_ratio'))} | "
            f"{_fmt_unknown(row.get('prominence_m'), '.1f')} |"
        )
    table_str = "\n".join(table_lines)

    # text_card is frozen in the DB (paired with its embedding) and never
    # modified; precomputed columns are appended dynamically here instead.
    def _extra_info(row) -> str:
        parts = []
        for name_key, dist_key, label in [
            ("nearest_school_name",   "nearest_school_dist_m",   "最寄り学校"),
            ("nearest_hospital_name", "nearest_hospital_dist_m", "最寄り病院"),
            ("nearest_police_name",   "nearest_police_dist_m",   "最寄り警察署"),
            ("nearest_fire_name",     "nearest_fire_dist_m",     "最寄り消防署"),
            ("nearest_post_name",     "nearest_post_dist_m",     "最寄り郵便局"),
        ]:
            nm, dv = row.get(name_key), row.get(dist_key)
            if nm and not (isinstance(nm, float) and pd.isna(nm)) and dv is not None and not pd.isna(dv):
                parts.append(f"・{label}: {nm} 約 {dv:.0f}m")
        mr = row.get("nearest_major_road_dist_m")
        if mr is not None and not (isinstance(mr, float) and pd.isna(mr)):
            parts.append(f"・幹線道路（国道・県道）まで: 約 {mr:.0f}m")
        wd = row.get("wooden_density_ratio")
        if wd is not None and not (isinstance(wd, float) and pd.isna(wd)):
            parts.append(f"・周辺100m圏の木造建物比率: {wd * 100:.0f}%")
        pm = row.get("prominence_m")
        if pm is not None and not (isinstance(pm, float) and pd.isna(pm)):
            parts.append(f"・周囲最高建物との高低差（突出度）: {pm:+.1f}m")
        rt, ra = row.get("roof_type_est"), row.get("roof_area_m2")
        if rt and not (isinstance(rt, float) and pd.isna(rt)):
            ra_str = f"（屋根面積 約 {ra:.0f}m2）" if ra is not None and not pd.isna(ra) else ""
            parts.append(f"・屋根種別: {rt}{ra_str}")
        return "\n[追加情報（前計算）]\n" + "\n".join(parts) if parts else ""

    # Cap full text_card attachment to the top 10 candidates (shortens the
    # overall prompt).
    FULL_CARD_LIMIT = 10
    card_list = []
    for i, (_, row) in enumerate(candidates.iterrows()):
        if i >= FULL_CARD_LIMIT:
            break
        card_list.append(f"[{i + 1}] {row['text_card']}{_extra_info(row)}")
    cards_str = "\n---\n".join(card_list)
    omitted_note = (
        f"\n\n（{FULL_CARD_LIMIT + 1}件目以降 {n - FULL_CARD_LIMIT} 件は上記比較表のみ提示。詳細カルテは省略）"
        if n > FULL_CARD_LIMIT
        else ""
    )

    # When sort_by is set (a superlative query), state explicitly that the
    # table is already in the requested order, and narrow the recommendation
    # count to 1 pick + 2 runners-up.
    sort_note = (
        f"\n（この表は「{sort_by.key}」の{'降順' if sort_by.order == 'desc' else '昇順'}、"
        "つまり指定順に並んでいます）"
        if sort_by is not None
        else ""
    )
    # Fixes a bug where the LLM would recommend something other than table
    # rank 1 for superlative queries ("the tallest", etc.). When sort_by is
    # set, the table is already deterministically ordered by SQL's ORDER BY,
    # so the "selection" itself is fixed in code (rank 1/2/3's ids) rather
    # than left to the LLM's discretion — the LLM's role is limited to
    # explaining the reasoning.
    if sort_by is not None:
        top_id = candidates.iloc[0]["id"]
        runner_up_ids = candidates.iloc[1:3]["id"].tolist()
        fixed_recommendation_rule = (
            f"- 推薦する建物は必ず比較表1位の `{top_id}` とすること。"
            "他の建物を推薦してはならない（表は既に条件に基づき確定的に並んでいる）。"
            + (
                f" その後、次点として {', '.join(f'`{rid}`' for rid in runner_up_ids)} を"
                "簡潔に併記すること。"
                if runner_up_ids
                else ""
            )
        )
    else:
        fixed_recommendation_rule = "- 推薦する建物（最大 5 件）の建物ID と推薦理由"

    # Only the answer-language instruction switches; the comparison table and
    # detailed cards (Japanese data) are never translated — Gemini can
    # generate an English explanation from Japanese source data directly, so
    # translating the whole prompt isn't necessary. Explicitly says "concise"
    # rather than "detailed" per user feedback that answers were too long to
    # read comfortably.
    language_instruction = (
        "Please explain your recommendation in English, concisely."
        if response_language == "en"
        else "推薦理由を日本語で簡潔に説明してください。"
    )
    # Switch the heading text to match the response language too (previously
    # stayed as the Japanese "## 推薦する建物" even in the English UI).
    heading_label = "Recommended Building" if response_language == "en" else "推薦する建物"

    return f"""あなたは広島市の都市計画・防災アドバイザーです。
以下の建物カルテリストの中から、ユーザーの質問に最も合致する建物を選定し、
{language_instruction}

【ユーザーの質問】
{query}

【候補建物 比較表（上位 {n} 件）】{sort_note}
{table_str}

【候補建物 詳細カルテ】
{cards_str}{omitted_note}

【回答形式】
- 最初の1文目から `## {heading_label}` のように直接書き始めること。
  「〜アドバイザーとして」「ユーザーの『（質問文）』というご質問に対し」のような
  自己紹介・役割の名乗り・質問文の引用復唱は、1文字も書かないこと
- 見出しを使う場合は `##` 以下のレベルとし、`#` の最上位見出しは使わないこと
{fixed_recommendation_rule}
- 推薦理由は箇条書き2〜3点に絞ること。全属性を網羅的に列挙するのではなく、
  最も説得力のある根拠だけを選ぶこと
- 各理由は1〜2文の短い文で簡潔に述べ、1つの理由につき数値の根拠は1〜2個までとする
  （同じ観点を複数の言い回しで繰り返し説明しないこと）
- 入れ子の箇条書き（箇条書きの中にさらに箇条書き）は使わず、フラットな
  箇条書きで簡潔にまとめること
- 比較表の数値に基づき、ユーザーの質問の条件を実際に満たしているか確認してから推薦すること
- リスク値・距離などの具体的な数値を引用すること
- 方位・日照・静けさ・地形に関する推薦は、比較表の壁面方位・冬日照・標高・
  幹線道路距離等の数値を根拠として明示すること
- 学校・病院・警察署・消防署・郵便局など施設への近さに関する推薦は、
  [追加情報（前計算）] ブロックの施設名と距離を根拠として示すこと
- 表やカルテにない情報を創作しないこと
- 該当する建物が見つからない場合はその旨を述べること
- データの制限事項（コード値未解決など）があれば付記すること"""


def generate_answer(
    query: str,
    candidates: pd.DataFrame,
    sort_by=None,
    response_language: str = "ja",
) -> str:
    """Generate an answer to the user's query via Gemini 3.5 Flash Lite.

    Uses `GEMINI_API_KEY`. Retries up to 3 times.

    Args:
        query: The user's natural-language query.
        candidates: Candidate rows, in ranking order.
        sort_by: Forwarded to `build_prompt()`.
        response_language: "ja" (default) or "en", forwarded to `build_prompt()`.

    Returns:
        The generated answer text.

    Raises:
        RuntimeError: If all retries are exhausted.
    """
    prompt = build_prompt(query, candidates, sort_by=sort_by, response_language=response_language)

    for attempt in range(3):
        try:
            return _generate_with_gemini(prompt)
        except Exception as exc:
            if attempt == 2:
                raise RuntimeError(f"回答生成に失敗: {exc}") from exc
            wait = 3 * (attempt + 1)
            print(f"  [RETRY {attempt + 1}] {wait}秒後リトライ...")
            time.sleep(wait)


def _generate_with_gemini(prompt: str) -> str:
    """Generate an answer with Gemini 3.5 Flash Lite (temperature=0 for reproducibility)."""
    from google import genai
    from google.genai import types

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY が .env に設定されていません。")

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt,
        config=types.GenerateContentConfig(temperature=0),
    )
    return response.text


# building_chunks.id format: a "bldg_" prefix + UUID (e.g. bldg_8aae00a2-e13d-4773-9c4f-51450c7963be).
_BUILDING_ID_PATTERN = re.compile(
    r"bldg_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)


def validate_answer(answer: str, candidates: pd.DataFrame, response_language: str = "ja") -> str:
    """Cross-check building IDs the LLM cited against the candidate set.

    Appends a note to the answer when it cites an ID absent from the
    candidates (a hallucination).

    Args:
        answer: The LLM's raw answer text.
        candidates: The candidate rows the answer was generated from.
        response_language: "ja" (default) or "en", for the appended note's language.

    Returns:
        `answer`, with a hallucination-warning note appended if applicable.
    """
    if not answer or candidates.empty:
        return answer

    mentioned_ids = set(_BUILDING_ID_PATTERN.findall(answer))
    if not mentioned_ids:
        return answer

    valid_ids = set(candidates["id"].tolist())
    unknown_ids = mentioned_ids - valid_ids
    if not unknown_ids:
        return answer

    # Switch the note's wording to match the response language too.
    if response_language == "en":
        note = (
            f"\n\n※ Note: The building ID(s) {', '.join(sorted(unknown_ids))} mentioned "
            "above are not in the search candidates. This may indicate a data error."
        )
    else:
        note = (
            f"\n\n※ 注記: 回答中の建物ID {', '.join(sorted(unknown_ids))} は"
            "検索候補に含まれていません。データの誤りの可能性があるためご注意ください。"
        )
    print(f"  [validate_answer] 候補に存在しない建物IDを検出: {unknown_ids}")
    return answer + note


# ============================================================
# Step 4-3: Integrated API entry point
# ============================================================

def hybrid_search(
    query: str,
    lon: float | None = None,
    lat: float | None = None,
    radius_m: float = 500.0,
    top_k: int = 30,
    use_query_parser: bool = True,
    skip_answer: bool = False,
    use_fts: bool = False,
    use_hyde: bool = False,
    embedding_source: str = "ruri",
    parsed_query_override: "ParsedQuery | None" = None,
    response_language: str = "ja",
) -> dict:
    """The integrated hybrid search API — this is the module's main entry point.

    When `use_query_parser=True` (default):
      1. Get a `ParsedQuery` from `parse_query(query)` (LLM query parsing).
      2. If `clarification_question` is set, skip search and return the question.
      3. If lon/lat weren't given but `location_name` was, resolve it via `geocode()`.
      4. Pass the ParsedQuery's filters into `vector_search()`.

    When `use_query_parser=False`: behaves as before query parsing existed
    (backward compatibility).

    Args:
        query: The natural-language query.
        lon: Search center longitude (WGS84). None means no spatial filter
            unless auto-geocoded via `location_name`.
        lat: Search center latitude (WGS84).
        radius_m: Spatial filter radius in meters.
        top_k: Number of candidates to fetch.
        use_query_parser: Enable LLM query parsing and geocoding.
        skip_answer: Skip LLM answer generation and return `answer=""` (used
            by evaluation scripts to conserve API quota).
        use_fts: Fuse BM25 full-text search with vector search via RRF
            (disabled for route="structured").
        use_hyde: Rewrite the semantic residual into a hypothetical card text
            before embedding (disabled for route="structured").
        embedding_source: "ruri" (default) or "gemini". "ruri" uses RURI v3
            310m (`embed_query_ruri`) for the query embedding and has
            `vector_search()` reference `building_chunks_ruri_embed`. Being
            local inference, it skips the ~1.25s API round trip — about
            0.085s once warm.
        parsed_query_override: When given, skips calling `parse_query(query)`
            and uses this `ParsedQuery` directly instead. An evaluation-only
            hook for fairly comparing `embedding_source="gemini"` vs `"ruri"`
            against the same parse result. None (default) calls
            `parse_query()` internally as usual.
        response_language: "ja" (default) or "en", forwarded to `build_prompt()`.

    Returns:
        A dict with `query`, `candidates`, `answer`, `elapsed_sec`,
        `parsed_query`, `geocoded_location`, `clarification_question`, `route`.
    """
    t0 = time.time()
    parsed_query_dict: dict | None = None
    geocoded_location: dict | None = None

    print(f"\n  クエリ: {query}")

    # =====================================================================
    # Query parsing / geocoding, then routing
    # =====================================================================
    from src.app.query_parser import parse_query, ParsedQuery
    from src.app.geocoder import geocode
    from src.app.router import classify_route

    search_lon = lon
    search_lat = lat
    search_radius = radius_m

    if use_query_parser:
        if parsed_query_override is not None:
            pq = parsed_query_override
            print("  クエリ解析: 既存のParsedQueryを再利用（parsed_query_override指定）")
        else:
            print("  クエリ解析中...")
            pq = parse_query(query, response_language=response_language)
        parsed_query_dict = {
            "location_name":          pq.location_name,
            "radius_m":               pq.radius_m,
            "height_min":             pq.height_min,
            "usage_include":          pq.usage_include,
            "structure_type":         pq.structure_type,
            "sort_by_height":         pq.sort_by_height,
            "clarification_question": pq.clarification_question,
            "risk_filters":           [vars(rf) for rf in pq.risk_filters],
            "distance_filters":       [vars(df) for df in pq.distance_filters],
            "fire_proof":             pq.fire_proof,
            "sort_by":                (vars(pq.sort_by) if pq.sort_by else None),
            "semantic_residual":      pq.semantic_residual,
            "orientation_filters":    [vars(of) for of in pq.orientation_filters],
            "sunlight":               pq.sunlight,
            "quiet":                  pq.quiet,
            "vertical_evacuation":    pq.vertical_evacuation,
            "height_max":             pq.height_max,
            "storeys_min":            pq.storeys_min,
            "storeys_max":            pq.storeys_max,
            "usage_exclude":          pq.usage_exclude,
            "structure_exclude":      pq.structure_exclude,
            "roof_type":              pq.roof_type,
            "wooden_dense":           pq.wooden_dense,
            "footprint_shape":        pq.footprint_shape,
        }
        print(f"  解析結果: location={pq.location_name}, height_min={pq.height_min}, "
              f"sort_by={pq.sort_by}, usage={pq.usage_include}, "
              f"structure={pq.structure_type}, risk_filters={pq.risk_filters}, "
              f"distance_filters={pq.distance_filters}, semantic_residual={pq.semantic_residual!r}")

        # If there's a clarification question, skip search and return it.
        if pq.clarification_question:
            print(f"  確認質問を返します: {pq.clarification_question[:50]}...")
            return {
                "query": query,
                "candidates": pd.DataFrame(),
                "answer": pq.clarification_question,
                "elapsed_sec": time.time() - t0,
                "parsed_query": parsed_query_dict,
                "geocoded_location": None,
                "clarification_question": pq.clarification_question,
                "route": None,
            }

        # Only auto-geocode when lon/lat weren't given manually.
        if search_lon is None and pq.location_name:
            coords = geocode(pq.location_name)
            if coords is not None:
                search_lon, search_lat = coords
                search_radius = pq.radius_m
                geocoded_location = {"lon": search_lon, "lat": search_lat}
        elif search_lon is not None:
            # Manual coordinates take precedence as-is (radius_m too).
            geocoded_location = {"lon": search_lon, "lat": search_lat}
    else:
        # Backward compat: behave as before query parsing existed (route is
        # always fixed to "semantic").
        pq = ParsedQuery()

    route = classify_route(pq) if use_query_parser else "semantic"
    print(f"  検索経路: {route}")
    print(f"  空間フィルタ: {'あり (lon={:.4f}, lat={:.4f}, r={}m)'.format(search_lon, search_lat, search_radius) if search_lon is not None else 'なし'}")

    # =====================================================================
    # Step 1: Embed the query (no API call when route="structured")
    # =====================================================================
    fts_query_text: str | None = None
    if route == "structured":
        query_vec = None
        print("  埋め込み生成をスキップ（route=structured）")
    else:
        embed_text = pq.semantic_residual if (use_query_parser and pq.semantic_residual) else query
        fts_query_text = embed_text
        if use_hyde:
            from src.app.search_fusion import hyde_rewrite
            print("  HyDE書き換え中...")
            hyde_text = hyde_rewrite(embed_text)
            print(f"  HyDE書き換え結果: {hyde_text!r}")
            embed_text = hyde_text
        print("  クエリ埋め込み生成中...")
        if embedding_source == "ruri":
            from src.app.ruri_query import embed_query_ruri
            query_vec = embed_query_ruri(embed_text)
        else:
            query_vec = embed_query(embed_text)

    # =====================================================================
    # Step 2: Vector search (HNSW + optional spatial filter + attribute filters)
    # =====================================================================
    print("  検索中...")
    rag_con = connect_rag()
    try:
        candidates = vector_search(
            rag_con, pq, route, query_vec,
            lon=search_lon, lat=search_lat, radius_m=search_radius, top_k=top_k,
            use_fts=use_fts, fts_query_text=fts_query_text,
            embedding_source=embedding_source,
        )
    finally:
        rag_con.close()

    print(f"  候補建物: {len(candidates)} 件")

    # Defensive re-check after the SQL filter (drops any candidates violating
    # a condition — see router.verify_candidates for why this is needed).
    from src.app.router import verify_candidates
    candidates, _removed_reasons = verify_candidates(candidates, pq)
    print(f"  検証後候補建物: {len(candidates)} 件")

    if candidates.empty:
        return {
            "query": query,
            "candidates": candidates,
            "answer": (
                "No matching buildings were found. Please modify your query or search area."
                if response_language == "en"
                else "候補建物が見つかりませんでした。クエリや検索範囲を変更してください。"
            ),
            "elapsed_sec": time.time() - t0,
            "parsed_query": parsed_query_dict,
            "geocoded_location": geocoded_location,
            "clarification_question": None,
            "route": route,
            "embedding_source": embedding_source,
            "response_language": response_language,
        }

    # =====================================================================
    # Step 3: LLM answer generation (temperature=0 for reproducibility)
    # =====================================================================
    if skip_answer:
        answer = ""
        print("  回答生成をスキップ（skip_answer=True）")
    else:
        print("  回答生成中（gemini）...")
        answer = generate_answer(
            query, candidates, sort_by=pq.sort_by,
            response_language=response_language,
        )
        answer = validate_answer(answer, candidates, response_language=response_language)

        # Post-hoc check for superlative queries (sort_by set): logs a
        # warning if the LLM recommended something other than table rank 1,
        # without modifying the answer itself.
        if pq.sort_by is not None:
            mentioned_ids = _BUILDING_ID_PATTERN.findall(answer)
            expected_top_id = candidates.iloc[0]["id"]
            if mentioned_ids and mentioned_ids[0] != expected_top_id:
                print(
                    f"  [WARN] sort_by指定クエリで比較表1位（{expected_top_id}）以外の"
                    f"建物（{mentioned_ids[0]}）が回答冒頭で言及されました"
                )

    elapsed = time.time() - t0
    print(f"  完了: {elapsed:.1f} 秒")

    return {
        "query": query,
        "candidates": candidates,
        "answer": answer,
        "elapsed_sec": elapsed,
        "parsed_query": parsed_query_dict,
        "geocoded_location": geocoded_location,
        "clarification_question": None,
        "route": route,
        "embedding_source": embedding_source,
        "response_language": response_language,
    }


# ============================================================
# TODO 4-3-2: main() — デモクエリ 2 件を実行してコンソール出力
# ============================================================

def run_phase4() -> None:
    """Phase 4 の動作確認: デモクエリ 2 件を実行してコンソール出力"""

    print("\n" + "=" * 60)
    print("Phase 4: ハイブリッド検索 -- デモ実行")
    print("=" * 60)

    # クエリ 1: 空間フィルタなし
    print("\n" + "-" * 60)
    print("クエリ 1: 高潮リスクが低く、駅から近い建物（空間フィルタなし）")
    print("-" * 60)
    result1 = hybrid_search(
        query="高潮リスクが低く、駅から近い建物",
        top_k=10,
    )
    print(f"\n【回答】\n{result1['answer']}")
    print(f"\n（所要時間: {result1['elapsed_sec']:.1f} 秒）")

    # クエリ 2: 空間フィルタあり（広島城周辺 500m）
    print("\n" + "-" * 60)
    print("クエリ 2: 耐火構造で避難所に近い建物（広島城周辺 500m）")
    print("-" * 60)
    result2 = hybrid_search(
        query="耐火構造で避難所に近い建物",
        lon=132.4625,
        lat=34.3955,
        radius_m=500.0,
        top_k=10,
    )
    print(f"\n【回答】\n{result2['answer']}")
    print(f"\n（所要時間: {result2['elapsed_sec']:.1f} 秒）")

    print("\n[SUCCESS] Phase 4 デモ完了")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        # コマンドライン引数からクエリを受け取って単発検索
        q = " ".join(sys.argv[1:])
        res = hybrid_search(query=q, top_k=10)
        print(f"\n【回答】\n{res['answer']}")
        print(f"\n（所要時間: {res['elapsed_sec']:.1f} 秒）")
    else:
        run_phase4()
